name: Generate list of publications from scopus

on:
  schedule:
    - cron: '0 0 * * 1' # At 00:00 on Monday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pybliometrics

      - name: execute python script
        env:
          SCOPUS_API_KEY: ${{ secrets.SCOPUS_API_KEY }}
        run: python _automation/update_publications.py $SCOPUS_API_KEY

      - name: commit updated list of publications
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated list of publications" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 